default:
  outputs:

    prod:
      type: materialize
      threads: 1
      host: 
      port: 6875
      user: 
      pass: 
      database: materialize
      schema: public
      # optionally use the cluster connection
      # parameter to specify the default cluster
      # for the connection
      cluster: default
      sslmode: require

  target: prod
